# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# I hope that works
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './test.ps1' # string. Required. Path to publish. Default: $(Build.ArtifactStagingDirectory).
    ArtifactName: 'unsigned-artifact'

- task: SubmitSigningRequest@4
  inputs:
    serviceConnectionName: 'test-qa'
    projectSlug: 'AzureDevOps'
    signingPolicySlug: 'test-signing'
    azureDevOpsArtifactName: 'unsigned-artifact'
    outputArtifactDirectory: './output'
    waitForCompletion: true
    waitForCompletionTimeoutInSeconds: '250'
    downloadSignedArtifactTimeoutInSeconds: '100'
    serviceUnavailableTimeoutInSeconds: '200'
    
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
